export const MOCK_AI_RECOMMEND = [
  {
    id: 1,
    title: '2026 Summer Internship R...',
    company: '(주) 한국존슨앤드존슨',
    employmentType: '체험형 인턴',
    location: '서울 용산구',
    imageUrl: 'https://via.placeholder.com/60',
    deadlineLabel: '~04.29',
  },
  {
    id: 2,
    title: '[현대자동차] 채용전환형 하계...',
    company: '현대자동차',
    employmentType: '인턴',
    location: '서울 서초구',
    imageUrl: 'https://via.placeholder.com/60',
    deadlineLabel: '~04.29',
  },
  {
    id: 3,
    title: '[네이버웹툰] 퍼포먼스 마케팅...',
    company: '네이버웹툰',
    employmentType: '체험형 인턴',
    location: '경기 성남시 분당구',
    imageUrl: 'https://via.placeholder.com/60',
    deadlineLabel: '~04.29',
  },
  {
    id: 4,
    title: '[라라스윗] 콘텐츠 마케팅 인턴...',
    company: '주식회사 라라스윗',
    employmentType: '체험형 인턴',
    location: '서울 강남구',
    imageUrl: 'https://via.placeholder.com/60',
    deadlineLabel: '~04.29',
  },
];
